{
 "title": "PV Power Ahoy",
 "description": "AHOY-DTU (https://github.com/grindylow/ahoy) delivers power metrics from inverter via MQTT to a MQTT (mosquitto) server. Telegraf subscribes that topic (\"inverter/#\") and writes everything to InfluxDB. The Dashboard consumes data from InfluxDB.",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "kwhPrice", "query": "0.23" },
   { "name": "ahoyTopic", "query": "inverter" },
   { "name": "ahoyInvertername", "query": "Hoymiles" },
   {
    "name": "country",
    "label": "Country",
    "query": "SHOW TAG VALUES FROM \"weather\" WITH KEY = \"country\""
   },
   {
    "name": "city",
    "label": "City",
    "query": "SHOW TAG VALUES FROM \"weather\" WITH KEY = \"city\""
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/P_AC') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch0/P_AC" }
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldDay') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch0/YieldDay" }
     ]
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldTotal') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "inverter/Hoymiles/ch0/YieldTotal"
      }
     ]
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "difference",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"value\")  / 1000 * $kwhPrice FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldDay') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * $kwhPrice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch0/YieldDay" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"temperature\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"city\" =~ /^$city$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" },
      { "condition": "AND", "key": "forecast", "operator": "=", "value": "*" }
     ]
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "cloudiness" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" },
      { "condition": "AND", "key": "forecast", "operator": "=", "value": "*" }
     ]
    }
   ]
  },
  {
   "title": "Sunrise time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "sunrise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Sunset time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "sunset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "city", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/P_AC') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch0/P_AC" }
     ]
    },
    {
     "alias": "Cloudiness",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"cloudiness\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"city\" =~ /^$city$/) AND $timeFilter GROUP BY time($__interval), \"country\", \"city\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "and", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily Production",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Daily Production",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldDay') AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch0/YieldDay" }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "U AC",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/U_AC') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch0/U_AC" }
       ]
      }
     ]
    },
    {
     "title": "Freq",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/Freq') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch0/Freq" }
       ]
      }
     ]
    },
    {
     "title": "Inverter Temp",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/Temp') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch0/Temp" }
       ]
      }
     ]
    },
    {
     "title": "Efficiency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/Efficiency') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        {
         "key": "topic",
         "operator": "=",
         "value": "inverter/Hoymiles/ch0/Efficiency"
        }
       ]
      }
     ]
    },
    {
     "title": "Power Limit",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/PowerLimit') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        {
         "key": "topic",
         "operator": "=",
         "value": "inverter/Hoymiles/ch0/PowerLimit"
        }
       ]
      }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Power West",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch1/P_DC') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch1/P_DC" }
       ]
      },
      {
       "alias": "Power Ost",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch2/P_DC') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "inverter/Hoymiles/ch2/P_DC" }
       ]
      },
      {
       "alias": "Irridation West",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch1/Irradiation') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "topic",
         "operator": "=",
         "value": "inverter/Hoymiles/ch1/Irradiation"
        }
       ]
      },
      {
       "alias": "Irridation Ost",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch2/Irradiation') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "topic",
         "operator": "=",
         "value": "inverter/Hoymiles/ch2/Irradiation"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}